<h2 class="text-2xl font-bold mt-8 mb-4" id="fleshing-out">Fleshing Out the Site (August 2022)</h2>
<section>
  <p class="mb-3">After my brief JavaScript adventure, I became dissatisfied with my explanation of quizbowl. The website referred to external explanations of quizbowl <a href="https://www.youtube.com/watch?v=spCgHocfBi0">here</a> and <a href="https://www.pace-nsc.org/resources/what-is-quizbowl-a-primer-and-faq-for-newcomers/">here</a>. While I thought these explanation were okay, they were still missing a little something. They focused too much on the "what" of quizbowl and not the "why". I wanted to create my own "What Is Quizbowl?" guide that built things up from first principles: one that spent less time on the granular details of quizbowl and more time on how we got here.</p>

  <p class="mb-3">After consulting with the <a class="text-blue-600 hover:text-blue-700" href="https://www.pace-nsc.org/about/">Partnership for Academic Competition Excellence</a>, I created a guide that used the now deprecated <b>30-20-10 model</b> from old quizbowl and the <b>pyramidal article model</b> from journalism to illustrate why quizbowl exists in its current form. I supplemented this with a "How to Write Questions" guide later on, which covered similar ground.</p>

  <p class="mb-3">Since I now had several distinct pages on the website, I decided to refactor the landing page and add a navbar. The Meet the Officers section was moved to its own page, as were Resources and Past Results. Once a topic was moved to its own page, I fleshed it out further to make the site feel more full. The <a class="text-blue-600 hover:text-blue-700" href="https://students.washington.edu/quizbowl/resources.html">Resources</a> page got one of the more dramatic overhauls, expanding from a short bulleted list to a well-organized clickable table of contents. The wide scope of the outbound links made it one of the best "Quick Links" quizbowl pages on the Internet (shown below).</p>

  <img class="mb-3" src="./img/quizbowl-resources.png" alt="Club Resources page">

  <p class="mb-3"><a class="text-blue-600 hover:text-blue-700" href="https://students.washington.edu/quizbowl/past-results.html">Past Results</a> also got a dramatic overhaul, turning into a comprehensive history of the club. There are detailed stats pages for every event that the club has ever attended, as well as a brief overview of every club season. At first, the page just chronicled the events of my tenure, but it now even covers events from the distant past. This culminated in a live interview with a "College Bowl" competitor from the 1960s, which you can find information about on the site.</p>
</section>