<h2 class="text-2xl font-bold mt-8 mb-4" id="java-edition">Java Edition (Summer 2020)</h2>
<section>
  <p class="mb-3">For a long time, the only programming language I knew really well was Java. I had touched various programming languages in elementary and middle school, but Java was the only fully-featured language I had used in a formal setting. Because of this, I first tried to interact with the Internet in Java.</p>

  <p class="mb-3">At first, the Popheads Chart was purely for me. I wanted to have a landing page of sorts for my own personal use, which would load in information from the web pages I most wanted to visit. I was unfamiliar with APIs at the time, so my first reaction was to use web scraping to get information. Early images of the Popheads Chart have been lost to time, but essentially I was loading data directly into the command line of my IDE.</p>

  <p class="mb-3">My web scraping approach was primitive at best. Because there was no centralized repository for the charts to my knowledge, I was forced to click through the author's post history in order to scrape the chart data. This was an arduous process that had me exploring technologies like Puppeteer and Selenium. I eventually arrived at the solution of using the old Reddit site UI, which has been kept around primarily for developers.</p>

  <p>Even with the old UI, there were still some really annoying problems associated with scraping the data. The chart files were stored in a hyperlink inside of a comment. There was no special identifier for this comment, so I just had to scan for the text and username. Sometimes the comment wasn't even a top-level comment, so if I didn't find it then I had to unroll the comment thread. Also, because the information was manually entered, a lot of it broke my parser. I ran into several date parsing issues caused by typos in particular. The code had to go through many hacky exception handling steps before it could actually run properly.</p>

  <p class="mb-3">Once I had everything up and running, I wanted to know if there was some way I could put the code on the Internet. I didn't know anything about web development, so I figured there was some easy way to simply mount Java code on the Internet. But after reading about technologies like Spring and Tomcat, I quickly became confused. I came to realize that web development was a different beast, and I was going to need to gain a lot more knowledge than just Java . I soon learned that this was going to take longer than I originally thought, so I put the project on the backburner for a few months.</p>
</section>